# .github/workflows/ci-cd-pipeline.yml
name: "Simple CI/CD Pipeline"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  # This will trigger your existing workflows automatically
  # No need to "call" them - they run on their own triggers

  integration-tests:
    name: "Integration Tests"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Wait for Deployments"
        run: |
          echo "Waiting for infrastructure and app deployment to complete..."
          echo "Your other workflows should be running in parallel."
          sleep 120  # Wait 2 minutes for deployments

      - name: "Run Integration Tests"
        run: |
          APP_URL="https://app-quoteapp-development.azurewebsites.net"

          echo "Running integration tests against: $APP_URL"

          # Test 1: Health Check
          echo "Testing health endpoint..."
          for i in {1..10}; do
            if curl -f "$APP_URL/health" >/dev/null 2>&1; then
              echo "Health check passed"
              break
            else
              echo "Attempt $i failed, retrying in 30s..."
              sleep 30
            fi
          done

          # Test 2: Main App
          echo "Testing main endpoint..."
          curl -f "$APP_URL" || echo "Main endpoint test failed"

          # Test 3: API Endpoints  
          echo "Testing API stats endpoint..."
          curl -f "$APP_URL/api/stats" || echo "API stats test failed"

          echo "Integration tests completed!"

      - name: "Post Test Results"
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## Integration Test Results

            **Status:** Tests completed
            **Environment:** development
            **App URL:** https://app-quoteapp-development.azurewebsites.net
            **Tested at:** ${new Date().toISOString()}

            Basic integration tests completed. Check logs for details.
            `;

            if (context.eventName === 'pull_request') {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
            }
